### ISSUE TITLE
webpack and its dev-server is assumed to be installed globally

### ISSUE THREAD

**Issue by scriptype** [vieuxio/example-chat-es6#2]
Following the instructions given in the readme, I was unable to run any webpack-related command. webpack is installed as a development dependency, so I ran it as `node_modules/.bin/webpack` but I don't think it's an elegant way.

Moreover, there's no clue about the `webpack-dev-server` dependency anywhere in the project. Since I've no prior experience with webpack I'm not sharp about the issue, but it seems like we should also have a devdep entry for it.

My idea to solve the cli problem is to hide these commands behind npm run scripts. It's possible to access the binaries inside the `node_modules/.bin` from npm scripts, directly with modules' names.

So, `scripts` may look like this (although it's open to suggestions for the names):

```js
"build:dev": "webpack",
"build:prod": "BUNDLE=1 webpack",
"server": "webpack-dev-server --port 1973"
```

I can create a PR applying my solution.

**Comment by dashersw** [comment]
That's actually very good! I am looking forward to it :) 👍
